# Generated by Django 4.2.3 on 2023-07-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
