# Generated by Django 4.2.3 on 2023-08-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoop', '0005_alter_product_options_alter_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='Azik', null=True, upload_to='category_image'),
        ),
    ]
